#include <init.h>

/* GIC SPI properties */
#define GIC_SPI_INT_BASE	32
#define GIC_SPI_NUM_INT		256

/* Base Address as seen by E1 */
#define OTRX_QSU0_CMU_BASE	0x50110000UL
#define OTRX_QSU1_CMU_BASE	0x51110000UL
#define OTRX_QSU2_CMU_BASE	0x52110000UL
#define OTRX_QSU3_CMU_BASE	0x53110000UL
#define OTRX_QSU4_CMU_BASE	0x6A110000UL
#define OTRX_QSU5_CMU_BASE	0x6B110000UL
#define OTRX_QSU6_CMU_BASE	0x6C110000UL
#define OTRX_QSU7_CMU_BASE	0x6D110000UL

#define DUAL_SU0_CMU_BASE	0x60110000UL
#define DUAL_SU1_CMU_BASE	0x61110000UL

#define PPU_PVT_MON_BASE	0x60480000UL

#define MCDMA0_BASE		0x60500000UL
#define MCDMA1_BASE		0x60501000UL
#define MCDMA2_BASE		0x60502000UL
#define MCDMA3_BASE		0x60503000UL

#define MXL0_SU_CMU_BASE	0x62110000UL
#define MXL0_CU_BASE		0x62600000UL
#define MXL1_SU_CMU_BASE	0x63110000UL
#define MXL1_CU_BASE		0x63600000UL

#define CRSS_SU0_CMU_BASE	0x64110000UL
#define CRSS_SU1_CMU_BASE	0x65110000UL
#define CRSS_SU2_CMU_BASE	0x66110000UL
#define CRSS_SU3_CMU_BASE	0x67110000UL

#define CRSS_QAU0_BASE		0x64600000UL
#define CRSS_QAU1_BASE		0x64640000UL
#define CRSS_QAU2_BASE		0x64680000UL
#define CRSS_QAU3_BASE		0x646C0000UL
#define CRSS_QAU4_BASE		0x64700000UL
#define CRSS_QAU5_BASE		0x64740000UL
#define CRSS_QAU6_BASE		0x64780000UL
#define CRSS_QAU7_BASE		0x647C0000UL

/* Offset of EVENT CLEAR Register */
#define REG_EVENT_CLEAR_OFFSET	0x10UL

/* Index for interrupts */
#define OTRX_QSU_OUT_EVT_0	(1 << 0)

#define DSU_SU_OUT_EVT_0	(1 << 0)
#define DSU_SU_OUT_EVT_1	(1 << 1)
#define DSU_SU_OUT_EVT_2	(1 << 2)
#define DSU_SU_OUT_EVT_3	(1 << 3)

#define MXL_SU_OUT_EVT_0	(1 << 0)
#define MXL_SU_OUT_EVT_1	(1 << 1)
#define MXL_SU_OUT_EVT_2	(1 << 2)
#define MXL_SU_OUT_EVT_3	(1 << 3)
#define MXL_IP_QUEUE_0		(1 << 0)
#define MXL_IP_QUEUE_1		(1 << 1)
#define MXL_OP_QUEUE_0		(1 << 2)
#define MXL_OP_QUEUE_1		(1 << 3)
#define MXL_FREE_HDR_PTR	(1 << 4)
#define MXL_FREE_PLD_PTR	(1 << 5)

#define CRSS_SU_OUT_EVT_0	(1 << 0)
#define CRSS_CRYPTO_ENG_0	(1 << 0)
#define CRSS_CRYPTO_ENG_1	(1 << 1)
#define CRSS_CRYPTO_ENG_2	(1 << 2)
#define CRSS_CRYPTO_ENG_3	(1 << 3)
#define CRSS_CRYPTO_ENG_4	(1 << 4)
#define CRSS_CRYPTO_ENG_5	(1 << 5)
#define CRSS_CMD_QUEUE		(1 << 6)
#define CRSS_STATUS_QUEUE	(1 << 7)

#define PPU_PVT_MON		(1 << 0)

#define NON_SU_EVT		0xFFFFFFFF

struct su_irq_info {
	mem_addr_t reg_evt_clr_base;
	uint32_t irq_idx;
};

static struct su_irq_info irq_info[GIC_SPI_NUM_INT] = {
	/* BSS Events */
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	/* BSS Peripheral Events */
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	/* IOSS Events */
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	/* CMN / IOMMU Events */
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	/* E1 CPU / PPU SS Events */
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	/* GPIO Events */
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	/* DDR Events */
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	/* PPU Events */
	{DUAL_SU0_CMU_BASE, DSU_SU_OUT_EVT_0},	/* DSU SU0 EVT 0 */
	{DUAL_SU0_CMU_BASE, DSU_SU_OUT_EVT_1},	/* DSU SU0 EVT 1 */
	{DUAL_SU0_CMU_BASE, DSU_SU_OUT_EVT_2},	/* DSU SU0 EVT 2 */
	{DUAL_SU0_CMU_BASE, DSU_SU_OUT_EVT_3},	/* DSU SU0 EVT 3 */
	{DUAL_SU1_CMU_BASE, DSU_SU_OUT_EVT_0},	/* DSU SU1 EVT 0 */
	{DUAL_SU1_CMU_BASE, DSU_SU_OUT_EVT_1},	/* DSU SU1 EVT 1 */
	{DUAL_SU1_CMU_BASE, DSU_SU_OUT_EVT_2},	/* DSU SU1 EVT 2 */
	{DUAL_SU1_CMU_BASE, DSU_SU_OUT_EVT_3},	/* DSU SU1 EVT 3 */
	{CRSS_QAU0_BASE, CRSS_CMD_QUEUE},	/* CRSS Command Queue 0 */
	{CRSS_QAU1_BASE, CRSS_CMD_QUEUE},	/* CRSS Command Queue 1 */
	{CRSS_QAU2_BASE, CRSS_CMD_QUEUE},	/* CRSS Command Queue 2 */
	{CRSS_QAU3_BASE, CRSS_CMD_QUEUE},	/* CRSS Command Queue 3 */
	{CRSS_QAU4_BASE, CRSS_CMD_QUEUE},	/* CRSS Command Queue 4 */
	{CRSS_QAU5_BASE, CRSS_CMD_QUEUE},	/* CRSS Command Queue 5 */
	{CRSS_QAU6_BASE, CRSS_CMD_QUEUE},	/* CRSS Command Queue 6 */
	{CRSS_QAU7_BASE, CRSS_CMD_QUEUE},	/* CRSS Command Queue 7 */
	{CRSS_QAU0_BASE, CRSS_STATUS_QUEUE},	/* CRSS Status Queue 0 */
	{CRSS_QAU1_BASE, CRSS_STATUS_QUEUE},	/* CRSS Status Queue 1 */
	{CRSS_QAU2_BASE, CRSS_STATUS_QUEUE},	/* CRSS Status Queue 2 */
	{CRSS_QAU3_BASE, CRSS_STATUS_QUEUE},	/* CRSS Status Queue 3 */
	{CRSS_QAU4_BASE, CRSS_STATUS_QUEUE},	/* CRSS Status Queue 4 */
	{CRSS_QAU5_BASE, CRSS_STATUS_QUEUE},	/* CRSS Status Queue 5 */
	{CRSS_QAU6_BASE, CRSS_STATUS_QUEUE},	/* CRSS Status Queue 6 */
	{CRSS_QAU7_BASE, CRSS_STATUS_QUEUE},	/* CRSS Status Queue 7 */
	{CRSS_QAU0_BASE, CRSS_CRYPTO_ENG_0},	/* CRSS Crypto Engine 0 */
	{CRSS_QAU0_BASE, CRSS_CRYPTO_ENG_1},	/* CRSS Crypto Engine 1 */
	{CRSS_QAU0_BASE, CRSS_CRYPTO_ENG_2},	/* CRSS Crypto Engine 2 */
	{CRSS_QAU0_BASE, CRSS_CRYPTO_ENG_3},	/* CRSS Crypto Engine 3 */
	{CRSS_QAU0_BASE, CRSS_CRYPTO_ENG_4},	/* CRSS Crypto Engine 4 */
	{CRSS_QAU0_BASE, CRSS_CRYPTO_ENG_5},	/* CRSS Crypto Engine 5 */
	{NON_SU_EVT, NON_SU_EVT},		/* Reserved */
	{NON_SU_EVT, NON_SU_EVT},		/* Reserved */
	{CRSS_SU0_CMU_BASE, CRSS_SU_OUT_EVT_0},	/* CRSS SU0 EVT 0 */
	{CRSS_SU1_CMU_BASE, CRSS_SU_OUT_EVT_0},	/* CRSS SU1 EVT 0 */
	{CRSS_SU2_CMU_BASE, CRSS_SU_OUT_EVT_0},	/* CRSS SU2 EVT 0 */
	{CRSS_SU3_CMU_BASE, CRSS_SU_OUT_EVT_0},	/* CRSS SU3 EVT 0 */
	{NON_SU_EVT, NON_SU_EVT},		/* Reserved */
	{NON_SU_EVT, NON_SU_EVT},		/* Reserved */
	{NON_SU_EVT, NON_SU_EVT},		/* Reserved */
	{PPU_PVT_MON_BASE, PPU_PVT_MON},	/* PPU PVT MON EVT */
	{MCDMA0_BASE, NON_SU_EVT},		/* TBD: MCDMA EVT 0 */
	{MCDMA1_BASE, NON_SU_EVT},		/* TBD: MCDMA EVT 1 */
	{MCDMA2_BASE, NON_SU_EVT},		/* TBD: MCDMA EVT 2 */
	{MCDMA3_BASE, NON_SU_EVT},		/* TBD: MCDMA EVT 3 */
	{MXL0_CU_BASE, MXL_IP_QUEUE_0},		/* MXL0 Input Queue 0 */
	{MXL0_CU_BASE, MXL_IP_QUEUE_1},		/* MXL0 Input Queue 1 */
	{MXL0_CU_BASE, MXL_OP_QUEUE_0},		/* MXL0 Output Queue 0 */
	{MXL0_CU_BASE, MXL_OP_QUEUE_1},		/* MXL0 Output Queue 1 */
	{MXL0_CU_BASE, MXL_FREE_HDR_PTR},	/* MXL0 Free Header Pointer */
	{MXL0_CU_BASE, MXL_FREE_PLD_PTR},	/* MXL0 Free Payload Pointer*/
	{MXL0_SU_CMU_BASE, MXL_SU_OUT_EVT_0},	/* MXL0 SU EVT 0 */
	{MXL0_SU_CMU_BASE, MXL_SU_OUT_EVT_1},	/* MXL0 SU EVT 1 */
	{MXL0_SU_CMU_BASE, MXL_SU_OUT_EVT_2},	/* MXL0 SU EVT 2 */
	{MXL0_SU_CMU_BASE, MXL_SU_OUT_EVT_3},	/* MXL0 SU EVT 3 */
	{MXL1_CU_BASE, MXL_IP_QUEUE_0},		/* MXL1 Input Queue 0 */
	{MXL1_CU_BASE, MXL_IP_QUEUE_1},		/* MXL1 Input Queue 1 */
	{MXL1_CU_BASE, MXL_OP_QUEUE_0},		/* MXL1 Output Queue 0 */
	{MXL1_CU_BASE, MXL_OP_QUEUE_1},		/* MXL1 Output Queue 1 */
	{MXL1_CU_BASE, MXL_FREE_HDR_PTR},	/* MXL1 Free Header Pointer */
	{MXL1_CU_BASE, MXL_FREE_PLD_PTR},	/* MXL1 Free Payload Pointer*/
	{MXL1_SU_CMU_BASE, MXL_SU_OUT_EVT_0},	/* MXL1 SU EVT 0 */
	{MXL1_SU_CMU_BASE, MXL_SU_OUT_EVT_1},	/* MXL1 SU EVT 1 */
	{MXL1_SU_CMU_BASE, MXL_SU_OUT_EVT_2},	/* MXL1 SU EVT 2 */
	{MXL1_SU_CMU_BASE, MXL_SU_OUT_EVT_3},	/* MXL1 SU EVT 3 */
	/* PPU E1 Events*/
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	/* CPUSS E1 Events */
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	/* Multi OS Sync Events */
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	/* TBD */
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	/* OTRX Events */
	{OTRX_QSU0_CMU_BASE, OTRX_QSU_OUT_EVT_0},	/* OTRX QSU0 EVT 0*/
	{OTRX_QSU1_CMU_BASE, OTRX_QSU_OUT_EVT_0},	/* OTRX QSU1 EVT 0*/
	{OTRX_QSU2_CMU_BASE, OTRX_QSU_OUT_EVT_0},	/* OTRX QSU2 EVT 0*/
	{OTRX_QSU3_CMU_BASE, OTRX_QSU_OUT_EVT_0},	/* OTRX QSU3 EVT 0*/
	{OTRX_QSU4_CMU_BASE, OTRX_QSU_OUT_EVT_0},	/* OTRX QSU4 EVT 0*/
	{OTRX_QSU5_CMU_BASE, OTRX_QSU_OUT_EVT_0},	/* OTRX QSU5 EVT 0*/
	{OTRX_QSU6_CMU_BASE, OTRX_QSU_OUT_EVT_0},	/* OTRX QSU6 EVT 0*/
	{OTRX_QSU7_CMU_BASE, OTRX_QSU_OUT_EVT_0},	/* OTRX QSU7 EVT 0*/
	/* Reserved */
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
	{NON_SU_EVT, NON_SU_EVT},
};

int su_clear_irq(uint32_t irq)
{
	if ((irq < GIC_SPI_INT_BASE) ||
	    (irq > GIC_SPI_INT_BASE + GIC_SPI_NUM_INT)) {
		printk("Invalid SPI number\n");
		return -EINVAL;
	}

	/* Get hwirq number in SPI range */
	irq -= GIC_SPI_INT_BASE;

	if (irq_info[irq].irq_idx == NON_SU_EVT) {
		printk("IRQ not mapped to SU.. Please check GIC SPI IRQ mappings\n");
		return -EINVAL;
	}

	printk("Reg: %lx\tVal: %d\n", (irq_info[irq].reg_evt_clr_base + REG_EVENT_CLEAR_OFFSET), irq_info[irq].irq_idx);
	sys_write32(irq_info[irq].irq_idx,
		   (irq_info[irq].reg_evt_clr_base + REG_EVENT_CLEAR_OFFSET));

	return 0;
}
